### ISSUE TITLE
JSON lists are crashing redis

### ISSUE THREAD

**Issue by viperjbm** [mattsta/krmt#7]
t_list.c line 49         redisPanic("Unknown list encoding");

is occurring when using JSON lists (including the donuts example list).  I'm on the latest dev version of dynamic redis branch, the latest dev version of krmt and the latest yajl as of today's date.

Here is the copied redis output:
17920:M 26 Feb 18:23:46.884 # ------------------------------------------------
17920:M 26 Feb 18:23:46.886 # !!! Software Failure. Press left mouse button to continue
17920:M 26 Feb 18:23:46.886 # Guru Meditation: "Unknown list encoding" #t_list.c:49
17920:M 26 Feb 18:23:46.888 # (forcing SIGSEGV in order to print the stack trace)
17920:M 26 Feb 18:23:46.889 # ------------------------------------------------
17920:M 26 Feb 18:23:46.890 #     Redis 2.9.999 crashed by signal: 11
17920:M 26 Feb 18:23:46.892 #     Failed assertion: <no assertion failed> (<no file>:0)
17920:M 26 Feb 18:23:46.893 # --- STACK TRACE
17920:M 26 Feb 18:23:46.896 # --- INFO OUTPUT
17920:M 26 Feb 18:23:46.902 # # Server
redis_version:2.9.999
redis_git_sha1:00000000
redis_git_dirty:0
redis_build_id:420be7a46a20f344
redis_mode:standalone
os:Linux 3.3.0 armv5tejl
arch_bits:32
multiplexing_api:epoll
gcc_version:4.6.3
process_id:17920
run_id:c4309badf0e415dce7595ef081e6e59de15ad4ed
tcp_port:6379
uptime_in_seconds:199
uptime_in_days:0
hz:10
lru_clock:2553218
config_file:
loaded_modules:1

# Clients
connected_clients:1
client_longest_output_list:0
client_biggest_input_buf:0
blocked_clients:0

# Memory
used_memory:736296
used_memory_human:719.04K
used_memory_rss:2215936
used_memory_peak:736296
used_memory_peak_human:719.04K
total_system_memory:94736384
total_system_memory_human:90.35M
used_memory_lua:26624
mem_fragmentation_ratio:3.01
mem_allocator:jemalloc-3.6.0
maxmemory_policy:noeviction

# Persistence
loading:0
rdb_changes_since_last_save:6
rdb_bgsave_in_progress:0
rdb_last_save_time:1898378427
rdb_last_bgsave_status:ok
rdb_last_bgsave_time_sec:-1
rdb_current_bgsave_time_sec:-1
aof_enabled:0
aof_rewrite_in_progress:0
aof_rewrite_scheduled:0
aof_last_rewrite_time_sec:-1
aof_current_rewrite_time_sec:-1
aof_last_bgrewrite_status:ok
aof_last_write_status:ok

# Stats
total_connections_received:1
total_commands_processed:2
instantaneous_ops_per_sec:0
total_net_input_bytes:812
total_net_output_bytes:152
instantaneous_input_kbps:0.00
instantaneous_output_kbps:0.00
rejected_connections:0
sync_full:0
sync_partial_ok:0
sync_partial_err:0
expired_keys:0
evicted_keys:0
keyspace_hits:2
keyspace_misses:0
pubsub_channels:0
pubsub_patterns:0
latest_fork_usec:0
migrate_cached_sockets:0

# Replication
role:master
connected_slaves:0
master_repl_offset:0
repl_backlog_active:0
repl_backlog_size:1048576
repl_backlog_first_byte_offset:0
repl_backlog_histlen:0

# CPU
used_cpu_sys:0.93
used_cpu_user:0.60
used_cpu_sys_children:0.00
used_cpu_user_children:0.00

# Commandstats
cmdstat_jsondocset:calls=1,usec=2367,usec_per_call=2367.00
cmdstat_jsondocget:calls=1,usec=1157,usec_per_call=1157.00

# Modules
module_<builtin>:filename=<builtin>,compiled_against=2.9.999,module_version=2.9.999,first_loaded=0,last_loaded=0,commands=get,set,setnx,setex,psetex,append,strlen,del,exists,setbit,getbit,setrange,getrange,substr,incr,decr,mget,rpush,lpush,rpushx,lpushx,linsert,rpop,lpop,brpop,brpoplpush,blpop,llen,lindex,lset,lrange,ltrim,lrem,rpoplpush,sadd,srem,smove,sismember,scard,spop,srandmember,sinter,sinterstore,sunion,sunionstore,sdiff,sdiffstore,smembers,sscan,zadd,zincrby,zrem,zremrangebyscore,zremrangebyrank,zremrangebylex,zunionstore,zinterstore,zrange,zrangebyscore,zrevrangebyscore,zrangebylex,zrevrangebylex,zcount,zlexcount,zrevrange,zcard,zscore,zrank,zrevrank,zscan,hset,hsetnx,hget,hmset,hmget,hincrby,hincrbyfloat,hdel,hlen,hkeys,hvals,hgetall,hexists,hscan,incrby,decrby,incrbyfloat,getset,mset,msetnx,randomkey,select,move,rename,renamenx,expire,expireat,pexpire,pexpireat,keys,scan,dbsize,auth,ping,echo,save,bgsave,bgrewriteaof,shutdown,lastsave,type,multi,exec,discard,sync,psync,replconf,flushdb,flushall,sort,info,monitor,ttl,pttl,persist,slaveof,role,debug,config,subscribe,unsubscribe,psubscribe,punsubscribe,publish,pubsub,watch,unwatch,cluster,restore,restore-asking,migrate,asking,readonly,readwrite,dump,object,client,eval,evalsha,slowlog,script,time,bitop,bitcount,bitpos,wait,command,pfselftest,pfadd,pfcount,pfmerge,pfdebug,latency
module_sh.matt.json:filename=../krmt/json.so,compiled_against=2.9.999,module_version=0.3,first_loaded=0,last_loaded=0,commands=hgetalljson,jsonwrap,jsondocvalidate,jsondocset,jsondocget,jsondocmget,jsondocdel,jsondocsetbyjson,jsondockeys,jsonfieldget,jsonfieldset,jsonfielddel,jsonfieldincrby,jsonfieldincrbyfloat,jsonfieldrpushx,jsonfieldrpop

# Cluster
cluster_enabled:0

# Keyspace
db0:keys=8,expires=0,avg_ttl=0
hash_init_value: 1898109944

17920:M 26 Feb 18:23:46.924 # --- CLIENT LIST OUTPUT
17920:M 26 Feb 18:23:46.925 # id=4 addr=127.0.0.1:57545 fd=6 name= age=196 idle=0 flags=N db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=32768 obl=0 oll=0 omem=0 events=r cmd=jsondocset

17920:M 26 Feb 18:23:46.925 # --- CURRENT CLIENT INFO
17920:M 26 Feb 18:23:46.926 # client: id=4 addr=127.0.0.1:57545 fd=6 name= age=196 idle=0 flags=N db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=32768 obl=0 oll=0 omem=0 events=r cmd=jsondocset
17920:M 26 Feb 18:23:46.926 # argv[0]: 'jsondocset'
17920:M 26 Feb 18:23:46.926 # argv[1]: 'donuts'
17920:M 26 Feb 18:23:46.926 # argv[2]: '{ "id": "0001", "type": "donut", "name": "Cake", "ppu": 0.55, "batters": { "batter": [ { "id": "1001", "type": "Regular" }, { "id": "1002", "type": "Chocolate" }, { "id": "1003", "type": "Blueberry" }, { "id": "1004", "type": "Devil's Food" } ] }, "topping": [ { "id": "5001", "type": "None" }, { "id": "5002", "type": "Glazed" }, { "id": "5005", "type": "Sugar" }, { "id": "5007", "type": "Powdered Sugar" }, { "id": "5006", "type": "Chocolate with Sprinkles" }, { "id": "5003", "type": "Chocolate" }, { "id": "5004", "type": "Maple" } ] }'
17920:M 26 Feb 18:23:46.927 # --- REGISTERS
17920:M 26 Feb 18:23:46.927 # --- FAST MEMORY TEST
17920:M 26 Feb 18:23:46.931 # Bio thread for job type #0 terminated
17920:M 26 Feb 18:23:46.935 # Bio thread for job type #1 terminated

**Comment by mattsta** [comment]
Thanks for the report!

This is actually a bug caused by new list improvements in Redis unstable/3.0+ versus how modules interact with lists.  (It is a downside of modules with Redis currently: modules rely heavily on implementation-level details of Redis that don't have clean abstractions; the internals of some modules are just a lot of direct copy/paste from Redis code to get things right.... then the Redis code changes across versions and modules break.  Whoops.)

Making the JSON module compatible with unstable/3.0+ is more work than benefit right now, so it's best to just use JSON with the 2.8 redis modules branch.

3.0 mostly adds clustering anyway, and the JSON module _definitely_ doesn't support that.  :)

I added a note to the krmt built process about version issues to hopefully not confuse other users in the future.
